
FROM openjdk:8u342

MAINTAINER inspection
EXPOSE 9091
LABEL version="1.0.1" description="moonbox springboot镜像" by="inspection"

COPY onlineInspect.jar /inspection/

CMD java -jar /inspection/onlineInspect.jar
